/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import modelo.dao.LivroDao;
import modelo.entidade.Autor;
import modelo.entidade.Categoria;
import modelo.entidade.Editora;
import modelo.entidade.Idioma;
import modelo.entidade.Livro;

/**
 *
 * @author Diogo
 */
public class LivroFrm extends javax.swing.JDialog {

    /**
     * Creates new form LivroFrm
     */
    public LivroFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.iniciarFrm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxfCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxfNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxfDescricao = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxfCategoria = new javax.swing.JTextField();
        BtnCategoria = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TxfAutor = new javax.swing.JTextField();
        BtnAutor = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TxfEditora = new javax.swing.JTextField();
        BtnEditora = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TxfIdioma = new javax.swing.JTextField();
        BtnIdioma = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxfPreco = new javax.swing.JFormattedTextField();
        TxfAnoPublicacao = new javax.swing.JFormattedTextField();
        TxfQtdePaginas = new javax.swing.JFormattedTextField();
        BtnDeletar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnNovo = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jTextField2.setText("jTextField2");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel5.setText("jLabel5");

        jLabel9.setText("jLabel9");

        jButton3.setText("jButton3");

        jFormattedTextField2.setText("jFormattedTextField2");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        TxfId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Código");

        TxfCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nome");

        TxfNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Descrição");

        TxfDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(TxfDescricao);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Preço");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Categoria");

        TxfCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BtnCategoria.setText("...");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Autor");

        TxfAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BtnAutor.setText("...");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Editora");

        TxfEditora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BtnEditora.setText("...");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Idioma");

        TxfIdioma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BtnIdioma.setText("...");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Ano de Publicação");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Quantidade de Páginas");

        TxfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        try {
            TxfAnoPublicacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TxfQtdePaginas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxfAnoPublicacao)
                            .addComponent(TxfQtdePaginas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxfId)
                            .addComponent(TxfCodigo)
                            .addComponent(TxfNome)
                            .addComponent(jScrollPane2)
                            .addComponent(TxfPreco)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxfCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                    .addComponent(TxfAutor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxfEditora, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxfIdioma, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnCategoria)
                                            .addComponent(BtnAutor, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(BtnEditora, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(BtnIdioma, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCategoria))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAutor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEditora))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TxfIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIdioma))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxfAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxfQtdePaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        BtnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        BtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarActionPerformed(evt);
            }
        });

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/novo.png"))); // NOI18N
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnNovo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDeletar)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarActionPerformed
        this.botaoDeletar();
    }//GEN-LAST:event_BtnDeletarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        this.botaoSalvar();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
       this.botaoNovo();
    }//GEN-LAST:event_BtnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LivroFrm dialog = new LivroFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAutor;
    private javax.swing.JButton BtnCategoria;
    private javax.swing.JButton BtnDeletar;
    private javax.swing.JButton BtnEditora;
    private javax.swing.JButton BtnIdioma;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JFormattedTextField TxfAnoPublicacao;
    private javax.swing.JTextField TxfAutor;
    private javax.swing.JTextField TxfCategoria;
    private javax.swing.JTextField TxfCodigo;
    private javax.swing.JTextPane TxfDescricao;
    private javax.swing.JTextField TxfEditora;
    private javax.swing.JTextField TxfId;
    private javax.swing.JTextField TxfIdioma;
    private javax.swing.JTextField TxfNome;
    private javax.swing.JFormattedTextField TxfPreco;
    private javax.swing.JFormattedTextField TxfQtdePaginas;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private Livro livro;
    private LivroDao livroDao;
    
    private Categoria categoria;
    private Autor autor;
    private Editora editora;
    private Idioma idioma;
    
    private void iniciarFrm() {
        livro = new Livro();
        BtnDeletar.setEnabled(false);
        BtnSalvar.setEnabled(true);
        BtnNovo.setEnabled(false);
        TxfId.setEditable(false);
        TxfCategoria.setEditable(false);
        TxfAutor.setEditable(false);
        TxfEditora.setEditable(false);
        TxfIdioma.setEditable(false);
    }
    
    private void obterDados() {
        livro.setCodigo(Integer.parseInt(TxfCodigo.getText()));
        livro.setNome(TxfNome.getText());
        livro.setDescricao(TxfDescricao.getText());
        livro.setPreco((double)TxfPreco.getValue());
        livro.setCategoria(categoria);
        livro.setAutor(autor);
        livro.setEditora(editora);
        livro.setIdioma(idioma);
        livro.setAnoPublicacao((int)TxfAnoPublicacao.getValue());
        livro.setQtdePaginas(Integer.parseInt(TxfQtdePaginas.getText()));
    }
    
    private void limparDados() {
        TxfId.setText("");
        TxfCodigo.setText("");
        TxfNome.setText("");
        TxfDescricao.setText("");
        TxfPreco.setText("");
        TxfCategoria.setText("");
        categoria = new Categoria();
        TxfAutor.setText("");
        autor = new Autor();
        TxfEditora.setText("");
        editora = new Editora();
        TxfIdioma.setText("");
        idioma = new Idioma();
        TxfAnoPublicacao.setText("");
        TxfQtdePaginas.setText("");
    }
    
    private void mostrarDados() {
        if (livro != null) {
            if (livro.getId() != null) {
                TxfId.setText(String.valueOf(livro.getId()));
            } else {
                TxfId.setText("");
            }
            TxfCodigo.setText(String.valueOf(livro.getCodigo()));
            TxfNome.setText(livro.getNome());
            TxfCodigo.setText(livro.getDescricao());
            TxfPreco.setText(String.valueOf(livro.getPreco()));
            TxfCategoria.setText(livro.getCategoria().getNome());
            TxfAutor.setText(livro.getAutor().getNome());
            TxfEditora.setText(livro.getEditora().getNome());
            TxfIdioma.setText(livro.getIdioma().getNome());
            TxfAnoPublicacao.setText(String.valueOf(livro.getAnoPublicacao()));
            TxfQtdePaginas.setText(String.valueOf(livro.getQtdePaginas()));
        }
        
        if (livro.getId() != null) {
            BtnNovo.setEnabled(false);
            BtnSalvar.setEnabled(true);
            BtnDeletar.setEnabled(false);
        } else {
            BtnNovo.setEnabled(true);
            BtnSalvar.setEnabled(true);
            BtnDeletar.setEnabled(true);
        }
    }
    
    public void setLivro(Livro livro) {
        this.livro = livro;
    }
    
    private void botaoNovo() {
        livro = new Livro();
        BtnNovo.setEnabled(false);
        BtnSalvar.setEnabled(true);
        BtnDeletar.setEnabled(false);
        this.mostrarDados();
    }
    
    private void botaoSalvar() {
        if (livroDao == null) {
            livroDao = new LivroDao();
        } 
        
        this.obterDados();
        
        if (livro.getCodigo() == null) {
            JOptionPane.showMessageDialog(null, "Informe o código do Livro");
        } else if ((livro.getNome() == null) || (livro.getNome().equals(""))) {
            JOptionPane.showMessageDialog(null, "Informe o nome do Livro");
        } else if ((livro.getDescricao() == null) || (livro.getDescricao().equals(""))) {
            JOptionPane.showMessageDialog(null, "Informe a descrição do Livro");
        } else if (livro.getPreco() == null) {
            JOptionPane.showMessageDialog(null, "Informe o preço do Livro");
        } else if (livro.getCategoria() == null) {
            JOptionPane.showMessageDialog(null, "Informe a categoria do Livro");
        } else if (livro.getAutor() == null) {
            JOptionPane.showMessageDialog(null, "Informe o autor do Livro");
        } else if (livro.getEditora() == null) {
            JOptionPane.showMessageDialog(null, "Informe a editora do Livro");
        } else if (livro.getIdioma() == null) {
            JOptionPane.showMessageDialog(null, "Informe o idioma do Livro");
        } else if (livro.getAnoPublicacao() == null) {
            JOptionPane.showMessageDialog(null, "Informe o ano de lançamento do Livro");
        } else if (livro.getQtdePaginas() == null) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade de páginas do Livro");
        } else {
            livroDao.save(livro);
            this.botaoNovo();
        }
    }
    
    private void botaoDeletar() {
        if (livroDao == null) {
            livroDao = new LivroDao();
        }
        livroDao.delete(livro);
        
        BtnNovo.setEnabled(false);
        BtnSalvar.setEnabled(true);
        BtnDeletar.setEnabled(false);
        
        livro = new Livro();
        limparDados();
        
    }
    
}
